[stable-only] Cap virtualenv/setuptools
With latest virtualenv release (20.24.0) and its bundled setuptools
version, stable/victoria gates started to fail [1], because setuptools
is not compatible with the pbr version (5.5.0) which is in victoria
branch's upper constraint [2]. pbr's next release (5.5.1) removed the
failing code, this is why the change is only needed in stable/victoria.

This patch caps virtualenv to <20.24.0 to fix stable/victoria's gate.

NOTE(elod.illes): while fixing virtualenv issue, another error came up
with tox itself [3], that is also fixed in this patch by capping
"inner tox".

[1] AttributeError: module 'setuptools.command.easy_install' has no attribute 'get_script_header'
[2] https://opendev.org/openstack/requirements/src/commit/636b6b3bde4b68ef27ac6b524cb888152eddf517/upper-constraints.txt#L44
[3] pass_env values cannot contain whitespace, use comma to have multiple values in a single line, invalid values found 'OS_DEBUG GENERATE_HASHES'

Change-Id: Ic9c3dd5cca7ae2c1d21fa3a7f516efd2757bd32e