baseproxy: stop requiring CONF.verbose
Option "verbose" from group "DEFAULT" was deprecated for removal during
Mitaka, and has been removing during Newton.

It has been dropped by oslo.config and nova-novncproxy now fails to
start:
NoSuchOptError: no such option in group DEFAULT: verbose

This patch aims to stop requiring CONF.verbose that does not exist
anymore.

Change-Id: I9533666db73390f28656ffcb1e84fadd51321e91
Closes-Bug: #1582103