Revert "Fix target_cell usage for scatter_gather_cells"
This reverts commit 3cc3cc453dc16e22365bea597c1be5bb0be57aeb.

We had determined that this commit had not actually fixed any bug or
issue with:

  TypeError: Can't upgrade a READER transaction to a WRITER
             mid-transaction

and the real fix was change Id24dea7465bafc1f6f58c4a121c4ffb35b7a634a.

This reverts the unnecessary commit in order to simplify the code and
it's possible that targeting the context before spawning a thread will
result in decreased cell cache lock contention once the threads are
spawned.

Related-Bug: #1722404

 Conflicts:
	nova/context.py

NOTE(melwitt): The conflict is due to change
I861b223ee46b0f0a31f646a4b45f8a02410253cf which is new since the
original commit had landed.

Change-Id: I3890d14d8679b96cfebcd735f3b03ec808730b5c