VMware: fix AttributeError: TaskInfo instance has no attribute 'name'
This happens in stable/icehouse with vCenter 6. This is a
stable/icehouse only change since this code was moved to oslo.vmware
and in Juno Nova was using this code from oslo.vwmware.

Furthermore, the _poll_task code in oslo.vmware was taken from cinder
which didn't have the call on task_info.name so the bug isn't there.

Change-Id: I729f1cdca1d4e02e31f26aa0e170c30be1a65288
Closes-bug: #1462424