db: Remove unnecessary 'insert()' argument
The function signature for this method is change in SQLAlchemy 2.x:

  TypeError: insert() takes 1 positional argument but 2 were given

We missed this previously as the deprecation checks in SQLAlchemy were
presumably checking for non-None values.

Change-Id: I4e366a0dbad56e739370b8bec0b84f6162f3d7a0
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>