Fixes bug 886263.
IndexError: pop index out of range on replace_uuid_with_id

(cherry picked from commit 10f93f567f4a164091d811765d1fdc39cdb36478)

Change-Id: I2f89bcc1675315c800e0d34bc09a268293a23caf