Fix nova-manage image_property show unexpected keyword
Reproduction steps:
1. Execute: nova-manage image_property show <vm_uuid> \
                            hw_vif_multiqueue_enabled
2. Observe:
  An error has occurred:
  Traceback (most recent call last):
    File "/var/lib/kolla/venv/lib/python3.9/
          site-packages/nova/cmd/manage.py", line 3394, in main
      ret = fn(*fn_args, **fn_kwargs)
  TypeError: show() got an unexpected keyword argument 'property'

Change-Id: I1349b880934ad9f44a943cf7de324d7338619d2e
Closes-Bug: #2016346
(cherry picked from commit 1c02c0da1702ab1f58e930782a8866ed683c3c7d)
(cherry picked from commit fc4b592d557cc92b7887ddb18fe2eb7588263e90)