Fix TypeError in nova-manage db archive_deleted_rows
If you run the archive_deleted_rows command without the
--max_rows option name but just pass in a value, it will
fail with a TypeError:

venv runtests: commands[0] | nova-manage db archive_deleted_rows 1000
An error has occurred:
Traceback (most recent call last):
  File "/home/user/git/nova/nova/cmd/manage.py", line 1924, in main
    ret = fn(*fn_args, **fn_kwargs)
TypeError: archive_deleted_rows() got multiple values for \
           keyword argument 'max_rows'

This fixes it by setting a dest and moving the default to the kwarg.

Change-Id: I1e60c571a8e9b875f89af6695f5427c801c8c53b
Closes-Bug: #1732593
(cherry picked from commit 0f464e55a856477a5b77ce8ce7efacf9bc139735)