Fix vol_usage_update() DB API tests.
vol_usage_update() method filters VolumeCache instances by
value of 'volume_id' column, which is of type varchar(36).
The problem is that a caller can pass 'volume_id' argument
as an integer value. On PostgreSQL this leads to the following
error when the SQL query is executed:

    ProgrammingError: (ProgrammingError) operator does not exist:
                      character varying = integer
    LINE 3: WHERE volume_usage_cache.volume_id = 1

Blueprint: db-api-tests-on-all-backends

Change-Id: I5ff1fa36d5494a15ec8b3bc1bfa9bb1c1af9fe97