Fix traceback when using s3.
Fix a regression that causes tracebacks in s3

Traceback (most recent call last):
  File "/opt/stack/nova/nova/image/s3.py", line 294, in delayed_create
     _update_image_state(context, image_uuid, 'downloading')
  File "/opt/stack/nova/nova/image/s3.py", line 286, in _update_image_state
  	headers)
 TypeError: update() takes at most 5 arguments (6 given)

This is due to 6e4539f397bfc5dbf9ec88ddc3968621815d576b

Fixes LP: #1031867

Change-Id: I6cf786999c623c0ca780a173dcba49354207e9c3
Signed-off-by: Chuck Short <chuck.short@canonical.com>