add functional repoducer for bug 2065927
Today if the write sys call to offline a cpu when
deleting an instnace fails due to an OSERROR or ValueERROR
the instance delete fails and the instance goes to error.

as reported in bug: #2065927 this can happen as a result of
OSError: [Errno 16] Device or resource busy if the vm is
deleted shortly after its started.

Related-Bug: #2065927
Change-Id: I1352a3a1e28cfe14ec8f32042ed35cb25e70338e
(cherry picked from commit ee581a5c9d1c0b7c0d8830a08f55fe8bc2fbcd0f)
(cherry picked from commit f1c46802b109db0b8e62f461ef0b432fa7c0984e)