Make compute rpcapi 'live_migration' backward compatible
This commit[1] added compute rpcapi version 4.2 which introduced a new
argument 'migration' when calling 'live_migration' method, but the code
did not ensure the backward compatibility with older version compute
node.

When calling 'live_migration' method with 'migration' argument on older
version(like Kilo) of nova compute node, a "TypeError: live_migration()
got an unexpected keyword argument 'migration'" will be threw up.

[1]https://github.com/openstack/nova/commit/2f4e64a7cf81de4a22fe2fc4210b1f795b1a3db4

Change-Id: Ie5c498d34e7c4c6573d611abd592c25f1bcb4f44
Closes-Bug: #1576048
(cherry picked from commit 34b8336a41e2896f0639c402f64a05247f475fea)