tox: Use basepython of python3.5
On hosts that provide Python 3.7, like Fedora 20, anything that doesn't
set an explicit Python 3 version is currently failing due to
zKVMCloudConnector explicitly stating it doesn't support Python < 3.6
(who knows why):

  $ tox -e docs
  ...
  Collecting zVMCloudConnector===1.2.2 (from -c https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt?h=stable/rocky (line 145))
    Downloading https://files.pythonhosted.org/packages/a1/da/f5a4432ebcbb630ce9a25d0ec81599fff7e473b5df7f73595783e39dba2d/zVMCloudConnector-1.2.2.tar.gz (183kB)
      ERROR: Complete output from command python setup.py egg_info:
      ERROR: Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-dci83kk9/zVMCloudConnector/setup.py", line 18, in <module>
          from zvmsdk import version as sdkversion
        File "/tmp/pip-install-dci83kk9/zVMCloudConnector/zvmsdk/version.py", line 29, in <module>
          raise RuntimeError('On Python 3, zvm sdk supports to Python 3.6')
      RuntimeError: On Python 3, zvm sdk supports to Python 3.6

Explicitly request a basepython of python3.5, which is what we supported
on stable/rocky to avoid. This stable only since the problem doesn't
happen on master, where a newer zVMCloudConnector package is available.

Change-Id: I99c8d115be695215a798a0fb2990279237ddf4d3
Signed-off-by: Stephen Finucane <sfinucan@redhat.com>
Stable-Only