Fix --max-count handling for nova-manage cell_v2 map_instances
Code is added to define destination for cell_uuid and max_count
argument, otherwise specifying --max-count fails with:

TypeError: map_instances() got an unexpected keyword argument 'max-count'

Change-Id: I9328a20b97977bfffa21df55bd4d60e711a406a7
Closes-Bug: #1715533