FakeLibvirtFixture: mock get_fs_info
A couple of recently-written [1][2] functional tests were mocking pieces
of the libvirt driver in ways that the existing FakeLibvirtFixture was
already doing [3].  This patch commonizes those tests to use the
fixture.

In addition, while those tests were being authored, they failed
intermittently with this symptom:

...
  File "nova/virt/libvirt/driver.py", line 6405, in get_available_resource
    disk_info_dict = self._get_local_gb_info()
  File "nova/virt/libvirt/driver.py", line 5663, in _get_local_gb_info
    info = libvirt_utils.get_fs_info(CONF.instances_path)
  File "nova/virt/libvirt/utils.py", line 370, in get_fs_info
    hddinfo = os.statvfs(path)
OSError: [Errno 2] No such file or directory: '/home/zuul/src/git.openstack.org/openstack/nova/instances'
...
Traceback (most recent call last):
  File "nova/tests/functional/libvirt/test_shared_resource_provider.py", line 45, in setUp
    self.host_uuid = self._get_provider_uuid_by_host(nodename)
  File "nova/tests/functional/integrated_helpers.py", line 410, in _get_provider_uuid_by_host
    'os-hypervisors?hypervisor_hostname_pattern=%s' % host).body
  File "nova/tests/functional/api/client.py", line 224, in api_get
    return APIResponse(self.api_request(relative_uri, **kwargs))
  File "nova/tests/functional/api/client.py", line 206, in api_request
    raise OpenStackApiNotFoundException(response=response)
nova.tests.functional.api.client.OpenStackApiNotFoundException: Item not found

It was discovered that the fix was mocking get_fs_info; so this patch
also adds that mock to FakeLibvirtFixture to avoid the race in future
tests using the fixture.

[1] https://review.openstack.org/#/c/560459/17/nova/tests/functional/libvirt/test_shared_resource_provider.py
[2] https://review.openstack.org/#/c/560317/17/nova/tests/functional/libvirt/test_report_cpu_traits.py
[3] https://github.com/openstack/nova/blob/162e55d07e98990399d2c595670883ceb2d4f1a9/nova/tests/unit/virt/libvirt/fakelibvirt.py#L1533-L1537

Change-Id: I4890406c92f538f7a5f270f70567f12e9531a2ad