Check service_ref before destroy
There is a race condition within the functional test when killing a
service is done before the service initialized the service_ref leading
to a

      File "/home/gibi/upstream/git/openstack/nova/nova/service.py", line 307, in kill
    self.service_ref.destroy()
    ^^^^^^^^^^^^^^^^^^^^^^^^

    AttributeError: 'NoneType' object has no attribute 'destroy'

Service.kill() only used in the test environment so this is basically a
test only change to check the service_ref before calling destroy()

Closes-Bug: #2160310

Change-Id: I1f1979d0736921133a993d9a0eda4ba34a4d1806
Signed-off-by: Balazs Gibizer <gibi@redhat.com>