Fix ValueError if invalid max_rows passed to db purge
In current behaviour, if user passes max_rows as string
value then it gives following error:
ValueError: invalid literal for int() with base 10:
'string value'

This patch fixes this issue by adding 'int' type validation
for max_rows.

Change-Id: I95273352466bbe23b0fb9094342260dc5b5f7d67
(cherry picked from commit 9540780e27520c6183dcaa9ca7865120d7dc60f4)