libvirt: 'video.vram' property must be an integer
The 'vram' property of the 'video' device must be an integer else
libvirt will spit the dummy out, e.g.

  libvirt.libvirtError: XML error: cannot parse video vram '8192.0'

The division operator in Python 3 results in a float, not an integer
like in Python 2. Use the truncation division operator instead.

Change-Id: Iebf678c229da4f455459d068cafeee5f241aea1f
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>
Closes-Bug: #1896496
(cherry picked from commit f2ca089bce842127e7d0644b38a11da9278db8ea)
(cherry picked from commit fd7c66f61c0b07cff82d93e0f884777949170857)
(cherry picked from commit 121e481a880b48ce800aafdeca0b8b086e2cddf3)