libvirt: Make `cpu_model_extra_flags` case-insensitive for real
When we introduced `cpu_model_extra_flags` config attribute (in
commit: 6b601b7 -- "libvirt: Allow to specify granular CPU feature
flags"), we said it was case-insensitive; but unfortunately I missed to
_really_ make it so (despite proposing code for it in one of the
revisions).

Address that mistake by making `cpu_model_extra_flags` case-insensitive
for real, from Nova's point of view.

NB: Internally, this patch is normalizing 'extra_flags' to _lower_
casing -- because CPU flags _must_ be lower case from libvirt's point of
view.  Nova must honour that; otherwise, launching instances with an
upper case CPU flag, 'FOO', will fail with: "libvirtError: internal
error: Unknown CPU feature FOO".

Related-Bug: #1750829
Change-Id: Ia7ff0566a5109c76c009f3a0c6199c4ba419cfb1
Reported-by: Daniel P. Berrangé <berrange@redhat.com>
Signed-off-by: Kashyap Chamarthy <kchamart@redhat.com>
(cherry picked from commit 8e438eda9bb16cdd3b627b93da2435572275b921)
(cherry picked from commit f9ab466c6d9bb657409356f29139a9edfbb98747)
(cherry picked from commit efa26e8dc24b5e828447fb78d0f54004054ae8b9)