Support quota for flavors
This commits add support for limiting the amount of instances a specific
project can spawn from a specific flavor by introducing optional quota
for flavors. This is tracked through an `extra_specs` key named
`quota:separate`, which needs to be set to `true`.

Such flavors can either require quota for their resources like CPU and
RAM or not. This is defined by another `extra_specs` key called
`quota:instance_only`. If set to `true`, only the instance quota and the
flavor quota needs to be available.

We use this feature for baremetal i.e. Ironic flavors and also for our
NUMA-enabled HANA flavors.

In reporting the quota usage per flavor, we need to support deleted
flavors. The `instance_type_id` column of the `instances` table does not
get updated, so we read the cached information from `instance_extra`
instead.

The querying happens with 2 queries instead of one, because they run
much faster individually than when trying to join them together in the
DB. MariaDB seemed to be unable to optimize this query and everything
else we tried didn't help.

There's code in Nova prohibiting re-computation of quota usage for ram
if cpu quota is already computed, because they come from the same
function. For optimization purposes, we extend that for `instances_`
resources. If "instances" is already in the usage data, our shared
function must have been called already. Therefore, if we encounter a
resource having a name starting with "instances_" - which should be only
true for resources we created for baremetal flavors - we can skip the
re-computation even if the resource's name is not in the usage data.

SQLAlchemy `func.sum()` returns `Decimal` on MariaDB. When the usage
limits are calculated unless explicitly converted to `int` we end up
with `Decimal` objects that cannot be JSONified and thus causing

    ValueError: Circular reference detected.

This code reads the information which flavor quota Nova should support
directly from the flavors. In a previous implementation from which we
still carry some code over, we used Nova's quota classes. There might be
still Ironic code calling these API extensions, but Nova doesn't
consider the data anymore.

To accommodate for dynamic quota and to keep better compatibility with
upstream's code, we introduce our own `SAPQuotaEngine` based on
upstream's `QuotaEngine`. This class holds the update functionality in
`_resources` by making it a property and all code accessing
`self._resources` reads the updated quota.
Since we want to get updates in without restarting our services, we use
a cache for the dynamic resources instead of only reading them once on
startup. This cache expires every 10 min by default, so updates are read
regularly.

We have to initialize the cache outside of the constructor similar to
`self._driver`, because `CONF` might not have been initialized when we
create the `SAPQuotaEngine` instance as module variable.

We also introduce `SAPCustomResource` to hold a property for checking if
usage was already computed for this resource.

Co-Authored-By: Jakob Karge <jakob.karge@sap.com>
Co-Authored-By: Dmitry Galkin <galkindmitrii@gmail.com>
Co-Authored-By: Andrew Karpow <andrew.karpow@sap.com>
Co-Authored-By: Fabian Wiesel <fabian.wiesel@sap.com>
Change-Id: Id59478e1d35f4bda73b1156556a3cf39bb62c9b6
Incorporated-Change-Id: If0e95cd1d62c00490dc86ca6273e07f8d2fd98ac
Incorporated-Change-Id: I73aa89b0b76a0620265fb20caf4a18eb1f5f8311
Incorporated-Change-Id: I956b910fe027978450ccbe8deba267a255d10767
Incorporated-Change-Id: I0f6f8605c64c2a9b3b2959eec6d21e5461fa3c7a
Incorporated-Change-Id: Iabddcaadc71839def6ce467c7159dabff7477e7e
Incorporated-Change-Id: Id278f29c3b9ad1ca94415b3df113711bd19ea51c
Incorporated-Change-Id: I8549a966b20e4b052261035dc0caf27d6581bcc8
Incorporated-Change-Id: Ib32b03cfa45ec05785b9fa67a9502922baa36ce4
Incorporated-Change-Id: Idd1f3ff029a72ad6f01f15eadec27f4cf9d2cd2b
Incorporated-Change-Id: Id6a629db0503b04c6a44185ab397a6c9c4b05715
Incorporated-Change-Id: I0c61ca6922e52f38e00242fed3d620a7cb3edaaf
Incorporated-Change-Id: I78b21227f800434029ac753464a8c3feee1e236f
Incorporated-Change-Id: I4b9f97246af9dad6574569deed6c1d1fcd72cbda
Incorporated-Change-Id: Idc007bea83f9198783dcd1af2d53d8934f28ede1
Incorporated-Change-Id: I4b30967b5f49ffc23cbb31c55d1d7fab6bd88a38
Incorporated-Change-Id: I57414cd78343bb26e603628f19e72bbc0fac2984
Incorporated-Change-Id: Ic2bb1e7b9223ca47e1ce944d7bbb711de277e31b
Incorporated-Change-Id: I8b05c08c977e56d7466b4942fdf6c927c841af1b
Incorporated-Change-Id: Iab249791285ba2daf1a368ceb9acfa798a897eec
Incorporated-Change-Id: Icd11dea083a1d02f5a06a98dcb4e421923b59008
Incorporated-Change-Id: I3984ff4e3b505235c78582bbf0ec57fc2111c886
Incorporated-Change-Id: I9689906bfc0a11acb3c4f985a2f1d6fe6eed6c16
Incorporated-Change-Id: Ifd35a26e4cda25eb98843919d76bd99483519f56
Incorporated-Change-Id: Iceba3c7820f9c6b9255ef6e00a9f49ed4677c12f
Incorporated-Change-Id: I87e686c0ce9124a74877a0783787820c36aecc35
Topic: quota