Add virtual interface before add fixed IP on nova-network
nova allow user to add fixed IP to an instance when the instance
is running. This action will fail due to no virtual interface
will be created before create fixed ip.
TypeError: 'NoneType' object is unsubscriptable will be reported.

(cherry picked from commit e08ce4de920b68c84ac45be8a657a95113688780)

Conflicts:
	nova/tests/unit/network/test_manager.py (file was moved)

Change-Id: I5885806d1965022816633d0105606e7aaf763b3a
Closes-Bug: #1294939