Fix exception translation when creating volume
Method `nova.volume.cinder.API#create` accepts `size` as the 3rd args,
but in wrapper of `nova.volume.cinder.translate_volume_exception`, the 3rd
parameter is volume_id. If we hit cinder exception when creating volumes
like the response body down below:
```
{"itemNotFound": {"message": "Volume type with name xxx could not be found.",
"code": 404}}
```
we may get exception in nova compute log like this:
```
BuildAbortException: Build of instance xxx aborted: Volume 40 could not be
found.
```
actually, `40` is volume size, not voluem id.

This could be a little misleading.

Closes-Bug: #1846532

Change-Id: If5b0c2f28773e0b2fcb008d5251fb69d950ca569
Signed-off-by: Fan Zhang <zh.f@outlook.com>
(cherry picked from commit 0f9311fae19e4e204cdc601acbe7dafc49c73661)
(cherry picked from commit 821506a50c13c73a2877e20ed9efc37a80e5dff8)
(cherry picked from commit c0313bce0685b5c1b5f57502711ea9d88d67a332)