db: Exclude the 'use_db_reconnect' option
Build on changes I714dce969088e17caaa1daddc881ebca6834e0f1, which
modified how we registered options for both the main and API databases,
and Iad2e4da4546b80a016e477577d23accb2606a6e4, which removed support for
experimental database reconnects, and start ignoring the
'use_db_reconnect' option. This means the option will no longer appear
in our documentation and won't be recognised by any of the validation
tooling if present in a nova.conf file.

No tests are present because I'm not entirely sure how to test the
thing. You can validate it manually though by attempting to set the
option in a test and watch things blow up like so:

  oslo_config.cfg.NoSuchOptError: no such option use_db_reconnect in
  group [database]

A second unnecessary 'deepcopy()' is removed. This was missed in change
I714dce969088e17caaa1daddc881ebca6834e0f1.

Change-Id: Ie7e4ccaf32f7222b8e305a38b48de7980744a98f
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>