Handle unicode characters in migration params
There can be unicode characters in the params for live migration, for
example, the guest domain name in the destination XML. We need to
convert those to bytes when we call migrateToURI3 under python2.

The existing code was just calling str() for this, but that will fail
with the error:

  UnicodeEncodeError: 'ascii' codec can't encode characters...

We need to encode the unicode characters to do conversion.

The existing unit test wasn't using any unicode characters in its test
data, so this scenario wasn't covered.

Conflicts:
	nova/tests/unit/virt/libvirt/test_guest.py
	nova/virt/libvirt/guest.py

NOTE(s10): Conflict is caused by Id9ee1feeadf612fa79c3d280cee3a614a74a00a7
not being in Queens.

Closes-Bug: #1768807

Change-Id: I4b34139a3c5e3e2b7cf7cbe50bdf3da3131b9b1c
(cherry picked from commit f046d8b54009978a3c83939dc190edbc1ebc09ae)
(cherry picked from commit 7520d159b5c33757fce398224e053183ff118663)