Add regression test for bug 1914777
This adds two tests to cover a regression where racing create and
delete requests could result in a user receiving a 500 error when
attempting to delete an instance:

  Unexpected exception in API method: AttributeError: 'NoneType' object
  has no attribute 'uuid'

Related-Bug: #1914777

Change-Id: I8249c572c6f727ef4ca434843106b9b57c47e585
(cherry picked from commit f7975d640ce1e9fa06d045d35177f07451716f0c)