Fix "resource" length in project_user_quotas table
"nova quota-update --injected-file-content-bytes 1024 --user <user> <tenant>"
is executed, the result is like the following:

$ nova quota-update --injected-file-content-bytes 1024 --user [..]
ERROR: The resource could not be found. (HTTP 404)
$

This is due to invalid length of resource in project_user_quotas table.
Current length is 25 and "injected_file_content_bytes" is shortened to
"injected_file_content_byt":

mysql> select resource from project_user_quotas;
+---------------------------+
| resource                  |
+---------------------------+
| injected_file_content_byt |
+---------------------------+

The resource of project_user_quotas table has been changed to invalid
length(25) since I56ad98d3702f53fe8cfa94093fea89074f7a5e90. The change
does not seem intention, that would be just a bug.
This patch fixes the problem.

Closes-Bug: 1227434

Change-Id: I3e080c30698dde62625eb477a85e1816191ff1e5