Indent domain removal to only be ran when it is not None.
When trying to remove failed instances I got the following trace:
(nova.rpc): TRACE: Traceback (most recent call last):
(nova.rpc): TRACE:   File "/usr/lib64/python2.7/site-packages/nova/rpc/impl_kombu.py", line 620, in _process_data
(nova.rpc): TRACE:     rval = node_func(context=ctxt, **node_args)
(nova.rpc): TRACE:   File "/usr/lib64/python2.7/site-packages/nova/exception.py", line 113, in wrapped
(nova.rpc): TRACE:     return f(*args, **kw)
(nova.rpc): TRACE:   File "/usr/lib64/python2.7/site-packages/nova/compute/manager.py", line 119, in decorated_function
(nova.rpc): TRACE:     function(self, context, instance_id, *args, **kwargs)
(nova.rpc): TRACE:   File "/usr/lib64/python2.7/site-packages/nova/compute/manager.py", line 569, in terminate_instance
(nova.rpc): TRACE:     self._delete_instance(context, instance_id)
(nova.rpc): TRACE:   File "/usr/lib64/python2.7/site-packages/nova/compute/manager.py", line 546, in _delete_instance
(nova.rpc): TRACE:     self._shutdown_instance(context, instance_id, 'Terminating', True)
(nova.rpc): TRACE:   File "/usr/lib64/python2.7/site-packages/nova/compute/manager.py", line 532, in _shutdown_instance
(nova.rpc): TRACE:     self.driver.destroy(instance, network_info, block_device_info, cleanup)
(nova.rpc): TRACE:   File "/usr/lib64/python2.7/site-packages/nova/virt/libvirt/connection.py", line 311, in destroy
(nova.rpc): TRACE:     virt_dom.undefine()
(nova.rpc): TRACE: AttributeError: 'NoneType' object has no attribute 'undefine'

Which is fixed by this commit.