Revert "Fixes Python 3 str issue in ConfigDrive creation"
This reverts commit 0134d88b750c304fa893ed4778806e56ec410857.

The commit was breaking tripleo-ci on stable/liberty with this error:
AttributeError: 'module' object has no attribute 'dump_as_bytes'

The root cause is that jsonutils.py from the stable/liberty version of
oslo.serialization does not have a dump_as_bytes method.

Partial-Bug: #1531881
Change-Id: I6a0c90fc319dc3d7fc4ed3347495758cbd7d0cc2