Do not import nova.conf into nova/exception.py
Clearly this is unused and results in:
 ArgsAlreadyParsedError: arguments already parsed: cannot register CLI
option

When trying to launch the privsep-helper in later patches

Change-Id: Ic44dc7ccbd1bdbbeb41bde923e65d2c78d183d2e