libvirt: properly decode error message from qemu guest agent
Some of error messages from qemu-guest-agent is
localized encoding.
We may get GB2312(Chinese charactors) from qga's error message
from a Chinese version of Windows.

nova didn't cover this senario, we may get errors like:
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6
    in position 138: ordinal not in range(128)

This patch will fix this issue by exception_to_unicode

Closes-bug: #1727643

Change-Id: I3b8bfaec8af0e9b4859dcfe7e35fc5bb26c208dc
Signed-off-by: Chen Hanxiao <chenhx@certusnet.com.cn>
(cherry picked from commit 13418faa17e1034db551c8d193a7b08e8b59ef9d)