Fakelibvirt migrateToURI3 should provide args according to libvirt doc
According to libvirt doc[1], migrateToURI3 supports
args(dconnuri, params, flags) but not logical_sum.
We call migrateToURI3 with arg flags in guest.py [2].

The wrong fake func may cause error in functional tests of nova.
With logs below:
  "/home/zuul/src/git.openstack.org/openstack/nova/nova/virt/libvirt/guest.py",
  line 669, in migrate'
  '    destination, params=params, flags=flags)'
  "TypeError: migrateToURI3() got an unexpected keyword argument 'flags'"

[1] https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainMigrateToURI3
[2] https://github.com/openstack/nova/blob/050e92/nova/virt/libvirt/guest.py#L668

Change-Id: I88d71bac7ddb69b9b63fb58dd8eaf6c048017933